<script setup lang="ts">
import { reactive, ref, watch } from 'vue'

type Exception = { date: string; type: 'NON_WORKING' | 'WORKING'; description: string | null }
type Calendar = { version: number; workingDays: string[]; reschedulingMode: 'MANUAL' | 'AUTOMATIC'; deadlinePolicy: 'ANTERIOR' | 'POSTERIOR'; allowUnscheduledTasks: boolean; exceptions: Exception[] }
type Impact = { task_id: string; before: { start: string | null; finish: string | null }; after: { start: string | null; finish: string | null } }
const props = defineProps<{ open: boolean }>()
const emit = defineEmits<{ close: []; saved: [] }>()
const days = [{ id: 'monday', label: 'Seg' }, { id: 'tuesday', label: 'Ter' }, { id: 'wednesday', label: 'Qua' }, { id: 'thursday', label: 'Qui' }, { id: 'friday', label: 'Sex' }, { id: 'saturday', label: 'Sáb' }, { id: 'sunday', label: 'Dom' }]
const calendar = reactive<Calendar>({ version: 1, workingDays: [], reschedulingMode: 'MANUAL', deadlinePolicy: 'ANTERIOR', allowUnscheduledTasks: true, exceptions: [] })
const loading = ref(false), saving = ref(false), simulating = ref(false), error = ref(''), impacts = ref<Impact[] | null>(null)

function headers(): HeadersInit { const token = document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content; return { 'Content-Type': 'application/json', Accept: 'application/json', ...(token ? { 'X-CSRF-TOKEN': token } : {}) } }
function replace(data: Calendar): void { calendar.version = data.version; calendar.workingDays = data.workingDays; calendar.reschedulingMode = data.reschedulingMode; calendar.deadlinePolicy = data.deadlinePolicy; calendar.allowUnscheduledTasks = data.allowUnscheduledTasks; calendar.exceptions = data.exceptions.map(item => ({ ...item })); impacts.value = null }
async function load(): Promise<void> { loading.value = true; error.value = ''; try { const response = await fetch('/api/v1/calendar', { headers: headers() }); if (!response.ok) throw new Error('Não foi possível carregar o calendário.'); replace((await response.json()).data) } catch (exception) { error.value = exception instanceof Error ? exception.message : 'Não foi possível carregar o calendário.' } finally { loading.value = false } }
function addException(): void { calendar.exceptions.push({ date: '', type: 'NON_WORKING', description: null }) }
function removeException(index: number): void { calendar.exceptions.splice(index, 1) }
function payload(confirmed = false): object { return { commandId: crypto.randomUUID(), expectedVersion: calendar.version, workingDays: calendar.workingDays, reschedulingMode: calendar.reschedulingMode, deadlinePolicy: calendar.deadlinePolicy, allowUnscheduledTasks: calendar.allowUnscheduledTasks, exceptions: calendar.exceptions, confirmed } }
async function simulate(): Promise<void> { if (calendar.workingDays.length === 0) { error.value = 'Selecione pelo menos um dia útil.'; return }; simulating.value = true; error.value = ''; try { const response = await fetch('/api/v1/calendar/simulate', { method: 'POST', headers: headers(), body: JSON.stringify(payload()) }); if (!response.ok) throw new Error('Não foi possível calcular o impacto do calendário.'); impacts.value = (await response.json()).data.changes } catch (exception) { error.value = exception instanceof Error ? exception.message : 'Não foi possível calcular o impacto.' } finally { simulating.value = false } }
async function save(): Promise<void> { if (calendar.reschedulingMode === 'MANUAL' && impacts.value === null) { await simulate(); return }; saving.value = true; error.value = ''; try { const response = await fetch('/api/v1/calendar', { method: 'PUT', headers: headers(), body: JSON.stringify(payload(calendar.reschedulingMode !== 'MANUAL' || impacts.value !== null)) }); if (!response.ok) throw new Error(response.status === 409 ? 'O calendário mudou em outro contexto. Recarregue antes de salvar.' : 'Não foi possível salvar o calendário.'); replace((await response.json()).data); emit('saved') } catch (exception) { error.value = exception instanceof Error ? exception.message : 'Não foi possível salvar o calendário.' } finally { saving.value = false } }
watch(() => props.open, open => { if (open) load() })
watch(() => [calendar.workingDays.join(','), calendar.reschedulingMode, calendar.deadlinePolicy, calendar.allowUnscheduledTasks, JSON.stringify(calendar.exceptions)], () => { impacts.value = null })
</script>

<template>
  <div v-if="open" class="account-scrim" @click.self="emit('close')"><aside class="calendar-panel" role="dialog" aria-modal="true" aria-labelledby="calendar-title"><header><div><span class="eyebrow">CONFIGURAÇÕES</span><h2 id="calendar-title">Calendário do projeto</h2></div><button aria-label="Fechar calendário" @click="emit('close')">×</button></header><section v-if="loading" class="account-muted">Carregando calendário…</section><section v-else><p>Defina os dias úteis e exceções que o planejamento deve respeitar.</p><fieldset><legend>Semana útil</legend><label v-for="day in days" :key="day.id"><input v-model="calendar.workingDays" type="checkbox" :value="day.id"> {{ day.label }}</label></fieldset><label>Modo de reagendamento<select v-model="calendar.reschedulingMode"><option value="MANUAL">Manual: confirmar impactos</option><option value="AUTOMATIC">Automático</option></select></label><label>Deadline em dia bloqueado<select v-model="calendar.deadlinePolicy"><option value="ANTERIOR">Dia útil anterior</option><option value="POSTERIOR">Próximo dia útil</option></select></label><label class="calendar-toggle"><input v-model="calendar.allowUnscheduledTasks" type="checkbox"> Permitir tarefas sem data</label><div class="calendar-exceptions"><b>Exceções</b><button class="soft-btn" @click="addException">Adicionar</button><p v-if="!calendar.exceptions.length" class="account-muted">Sem exceções cadastradas.</p><div v-for="(exception,index) in calendar.exceptions" :key="index" class="exception-row"><input v-model="exception.date" type="date" aria-label="Data da exceção"><select v-model="exception.type" aria-label="Tipo da exceção"><option value="NON_WORKING">Não útil</option><option value="WORKING">Útil</option></select><button aria-label="Remover exceção" @click="removeException(index)">×</button></div></div><section v-if="impacts!==null" class="calendar-impact" role="status"><b>{{impacts.length?'Impacto previsto':'Sem tarefas afetadas'}}</b><ul v-if="impacts.length"><li v-for="impact in impacts" :key="impact.task_id">{{impact.task_id}}: {{impact.before.start}}–{{impact.before.finish}} → {{impact.after.start}}–{{impact.after.finish}}</li></ul><button class="soft-btn" @click="impacts=null">Descartar prévia</button></section><p v-if="error" class="account-error" role="alert">{{ error }}</p></section><footer><button class="soft-btn" @click="emit('close')">Cancelar</button><button class="primary" :disabled="saving||simulating" @click="save">{{saving?'Salvando…':simulating?'Calculando…':calendar.reschedulingMode==='MANUAL'&&impacts===null?'Simular impacto':'Confirmar calendário'}}</button></footer></aside></div>
</template>
