<script setup lang="ts">
import { ref, watch } from 'vue'

type Event = { id: string; action: string; origin: string; subjectType: string | null; subjectId: string | null; causationId: string | null; occurredAt: string; before: Record<string, unknown> | null; after: Record<string, unknown> | null }
const props = defineProps<{ open: boolean }>()
const emit = defineEmits<{ close: [] }>()
const events = ref<Event[]>([]), loading = ref(false), error = ref(''), cursor = ref<string | null>(null), hasMore = ref(false), origin = ref(''), action = ref('')

async function load(reset = true): Promise<void> { loading.value = true; error.value = ''; try { const params = new URLSearchParams(); if (!reset && cursor.value) params.set('cursor', cursor.value); if (origin.value) params.set('origin', origin.value); if (action.value) params.set('action', action.value); const response = await fetch(`/api/v1/audit-events?${params}`, { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error('Não foi possível carregar o histórico.'); const body = await response.json(); events.value = reset ? body.data : [...events.value, ...body.data]; cursor.value = body.meta.nextCursor; hasMore.value = body.meta.hasMore } catch (exception) { error.value = exception instanceof Error ? exception.message : 'Não foi possível carregar o histórico.' } finally { loading.value = false } }
watch(() => props.open, open => { if (open) load() })
</script>

<template><div v-if="open" class="account-scrim" @click.self="emit('close')"><aside class="history-panel" role="dialog" aria-modal="true" aria-labelledby="history-title"><header><div><span class="eyebrow">RASTREABILIDADE</span><h2 id="history-title">Histórico do projeto</h2></div><button aria-label="Fechar histórico" @click="emit('close')">×</button></header><section><div class="history-filters"><label>Origem<select v-model="origin" @change="load()"><option value="">Todas</option><option value="user">Usuário</option><option value="web">Web</option><option value="worker">Processamento</option><option value="webhook">Webhook</option></select></label><label>Ação<select v-model="action" @change="load()"><option value="">Todas</option><option value="calendar.updated">Calendário</option><option value="recalculation.created">Operação criada</option><option value="recalculation.completed">Operação concluída</option><option value="recalculation.conflict">Conflito</option></select></label></div><p v-if="loading&&!events.length" class="account-muted">Carregando histórico…</p><p v-else-if="!events.length" class="account-muted">Nenhum evento para estes filtros.</p><ol class="history-list"><li v-for="event in events" :key="event.id"><b>{{ event.action }}</b><small>{{ new Date(event.occurredAt).toLocaleString('pt-BR') }} · {{ event.origin }}</small><span v-if="event.subjectId">Item: {{ event.subjectId }}</span><span v-if="event.causationId">Causa: {{ event.causationId }}</span></li></ol><p v-if="error" class="account-error" role="alert">{{error}}</p><button v-if="hasMore" class="soft-btn" :disabled="loading" @click="load(false)">{{loading?'Carregando…':'Carregar mais'}}</button></section></aside></div></template>
