<script setup lang="ts">
import { onMounted, ref } from 'vue'
type Project={id:string;name:string;taskCount:number;progress:number;overdueTaskCount:number;role:string}; type Invitation={id:string;project_id:string;project_name:string;role:'editor'|'reader'}
const emit=defineEmits<{open:[id:string]}>(); const projects=ref<Project[]>([]), invitations=ref<Invitation[]>([]), loading=ref(true), name=ref(''), creating=ref(false), accepting=ref<string|null>(null), error=ref('')
const csrfHeaders=():Record<string,string>=>{const token=document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content;return token?{'X-CSRF-TOKEN':token}:{}}
async function load(){loading.value=true;error.value='';try{const [projectResponse,invitationResponse]=await Promise.all([fetch('/api/v1/projects'),fetch('/api/v1/invitations')]);if(!projectResponse.ok||!invitationResponse.ok)throw new Error('Não foi possível carregar os projetos.');projects.value=(await projectResponse.json()).data;invitations.value=(await invitationResponse.json()).data}catch(e){error.value=e instanceof Error?e.message:'Erro inesperado'}finally{loading.value=false}}
async function create(){if(!name.value.trim())return;creating.value=true;error.value='';try{const r=await fetch('/api/v1/projects',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json',...csrfHeaders()},body:JSON.stringify({name:name.value,commandId:crypto.randomUUID()})});if(!r.ok)throw new Error('Não foi possível criar o projeto.');emit('open',(await r.json()).data.id)}catch(e){error.value=e instanceof Error?e.message:'Erro inesperado'}finally{creating.value=false}}
async function accept(invitation:Invitation){accepting.value=invitation.id;error.value='';try{const r=await fetch(`/api/v1/invitations/${invitation.id}/accept`,{method:'POST',headers:{Accept:'application/json',...csrfHeaders()}});if(!r.ok)throw new Error('Não foi possível aceitar o convite.');emit('open',(await r.json()).data.projectId)}catch(e){error.value=e instanceof Error?e.message:'Erro inesperado'}finally{accepting.value=null}}
onMounted(load)
</script>
<template><main class="main project-dashboard"><header class="commandbar"><div class="title-block"><p class="eyebrow">SEUS PROJETOS</p><h1>Projetos</h1></div></header><form class="create-task" @submit.prevent="create"><input v-model="name" aria-label="Nome do projeto" placeholder="Nome do novo projeto"><button class="primary" :disabled="creating||!name.trim()">{{creating?'Criando…':'Novo projeto'}}</button></form><p v-if="error" class="workspace-state">{{error}}</p><p v-else-if="loading" class="loading">Carregando projetos…</p><template v-else><section v-if="invitations.length" class="stats-row"><article v-for="invitation in invitations" :key="invitation.id" class="project-card"><b>Convite: {{invitation.project_name}}</b><small>{{invitation.role==='editor'?'Pode alterar':'Somente leitura'}}</small><button class="primary" :disabled="accepting===invitation.id" @click="accept(invitation)">{{accepting===invitation.id?'Aceitando…':'Aceitar convite'}}</button></article></section><p v-if="!projects.length" class="workspace-state">Você ainda não tem projetos. Crie o primeiro acima.</p><section v-else class="stats-row"><button v-for="project in projects" :key="project.id" class="project-card" @click="emit('open',project.id)"><b>{{project.name}}</b><small>{{project.taskCount}} tarefas · {{project.progress}}% · {{project.overdueTaskCount}} atrasadas</small></button></section></template></main></template>
