<?php

use App\Http\Controllers\Api\Documents\DerivationRunController;
use App\Http\Controllers\Api\Documents\DocumentContentController;
use App\Http\Controllers\Api\Documents\DocumentController;
use App\Http\Controllers\Api\Documents\DocumentDerivationController;
use App\Http\Controllers\Api\Documents\DocumentRevisionController;
use App\Http\Controllers\Api\Documents\OfflineManifestController;
use App\Http\Controllers\Api\Documents\ProjectTagController;
use App\Http\Controllers\Api\ObservabilityController;
use App\Http\Controllers\Api\ProjectController;
use App\Http\Controllers\Api\SessionController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::middleware('web')->group(function () {
        Route::get('/health', [ObservabilityController::class, 'health']);
        Route::get('/ready', [ObservabilityController::class, 'readiness']);
        Route::get('/metrics', [ObservabilityController::class, 'metrics'])->middleware('throttle:30,1');
        Route::middleware('auth')->group(function () {
            Route::get('/me', [SessionController::class, 'show']);
            Route::get('/sessions', [SessionController::class, 'index']);
            Route::delete('/sessions/{sessionId}', [SessionController::class, 'destroy']);
            Route::get('/projects', [ProjectController::class, 'index']);
            Route::post('/projects', [ProjectController::class, 'store']);
            Route::get('/projects/{projectId}/workspace', [ProjectController::class, 'workspace']);
            Route::get('/projects/{projectId}/documents', [DocumentController::class, 'index']);
            Route::post('/projects/{projectId}/documents', [DocumentController::class, 'store']);
            Route::get('/projects/{projectId}/documents/{documentId}', [DocumentController::class, 'show']);
            Route::patch('/projects/{projectId}/documents/{documentId}', [DocumentController::class, 'update']);
            Route::delete('/projects/{projectId}/documents/{documentId}', [DocumentController::class, 'destroy']);
            Route::post('/projects/{projectId}/documents/{documentId}/restore', [DocumentController::class, 'restore']);
            Route::get('/projects/{projectId}/documents/{documentId}/revisions', [DocumentRevisionController::class, 'index']);
            Route::post('/projects/{projectId}/documents/{documentId}/revisions', [DocumentRevisionController::class, 'store']);
            Route::match(['get', 'head'], '/projects/{projectId}/revisions/{revisionId}/content', DocumentContentController::class);
            Route::get('/projects/{projectId}/documents/{documentId}/derivations', [DocumentDerivationController::class, 'index']);
            Route::post('/projects/{projectId}/documents/{documentId}/derivations', [DocumentDerivationController::class, 'store']);
            Route::get('/projects/{projectId}/derivations/{derivationId}', [DocumentDerivationController::class, 'show']);
            Route::patch('/projects/{projectId}/derivations/{derivationId}', [DocumentDerivationController::class, 'update']);
            Route::post('/projects/{projectId}/derivations/{derivationId}/regenerate', [DocumentDerivationController::class, 'regenerate']);
            Route::delete('/projects/{projectId}/derivations/{derivationId}', [DocumentDerivationController::class, 'destroy']);
            Route::get('/projects/{projectId}/derivation-runs/{runId}', DerivationRunController::class);
            Route::get('/projects/{projectId}/tags', [ProjectTagController::class, 'index']);
            Route::post('/projects/{projectId}/tags', [ProjectTagController::class, 'store']);
            Route::patch('/projects/{projectId}/tags/{tagId}', [ProjectTagController::class, 'update']);
            Route::delete('/projects/{projectId}/tags/{tagId}', [ProjectTagController::class, 'destroy']);
            Route::get('/projects/{projectId}/offline-manifest', OfflineManifestController::class);
            Route::post('/projects/{projectId}/sections', [ProjectController::class, 'createSection']);
            Route::put('/projects/{projectId}/sections/{sectionId}', [ProjectController::class, 'updateSection']);
            Route::post('/projects/{projectId}/structure/move', [ProjectController::class, 'moveStructureItem']);
            Route::post('/projects/{projectId}/tasks', [ProjectController::class, 'createTask']);
            Route::post('/projects/{projectId}/tasks/{taskId}/duplicate', [ProjectController::class, 'duplicateTask']);
            Route::put('/projects/{projectId}/tasks/{taskId}', [ProjectController::class, 'updateTask']);
            Route::patch('/projects/{projectId}/tasks/{taskId}/completion', [ProjectController::class, 'setTaskCompletion']);
            Route::post('/projects/{projectId}/tasks/{taskId}/checklist', [ProjectController::class, 'createChecklistItem']);
            Route::put('/projects/{projectId}/tasks/{taskId}/checklist/{itemId}', [ProjectController::class, 'updateChecklistItem']);
            Route::put('/projects/{projectId}/tasks/{taskId}/checklist', [ProjectController::class, 'reorderChecklist']);
            Route::delete('/projects/{projectId}/tasks/{taskId}/checklist/{itemId}', [ProjectController::class, 'deleteChecklistItem']);
            Route::delete('/projects/{projectId}/tasks/{taskId}', [ProjectController::class, 'deleteTask']);
            Route::get('/projects/{projectId}/tasks/{taskId}/context', [ProjectController::class, 'taskContext']);
            Route::post('/projects/{projectId}/tasks/{taskId}/tables', [ProjectController::class, 'createTable']);
            Route::post('/projects/{projectId}/tasks/{taskId}/tables/{tableId}/edit-lock', [ProjectController::class, 'acquireTableLock']);
            Route::put('/projects/{projectId}/tasks/{taskId}/tables/{tableId}/edit-lock', [ProjectController::class, 'renewTableLock']);
            Route::delete('/projects/{projectId}/tasks/{taskId}/tables/{tableId}/edit-lock', [ProjectController::class, 'releaseTableLock']);
            Route::put('/projects/{projectId}/tasks/{taskId}/tables/{tableId}', [ProjectController::class, 'updateTable']);
            Route::delete('/projects/{projectId}/tasks/{taskId}/tables/{tableId}', [ProjectController::class, 'deleteTable']);
            Route::post('/projects/{projectId}/tasks/{taskId}/comments', [ProjectController::class, 'createComment']);
            Route::put('/projects/{projectId}/tasks/{taskId}/comments/{commentId}', [ProjectController::class, 'updateComment']);
            Route::delete('/projects/{projectId}/tasks/{taskId}/comments/{commentId}', [ProjectController::class, 'deleteComment']);
            Route::delete('/projects/{projectId}/sections/{sectionId}', [ProjectController::class, 'deleteSection']);
            Route::post('/projects/{projectId}/dependencies', [ProjectController::class, 'createDependency']);
            Route::put('/projects/{projectId}/dependencies/{dependencyId}', [ProjectController::class, 'updateDependency']);
            Route::delete('/projects/{projectId}/dependencies/{dependencyId}', [ProjectController::class, 'deleteDependency']);
            Route::post('/projects/{projectId}/people', [ProjectController::class, 'createPerson']);
            Route::put('/projects/{projectId}/people/{personId}', [ProjectController::class, 'updatePerson']);
            Route::post('/projects/{projectId}/people/{personId}/block', [ProjectController::class, 'blockPerson']);
            Route::delete('/projects/{projectId}/people/{personId}', [ProjectController::class, 'deletePerson']);
            Route::post('/projects/{projectId}/invitations', [ProjectController::class, 'inviteMember']);
            Route::post('/projects/{projectId}/invitations/{invitationId}/resend', [ProjectController::class, 'resendInvitation']);
            Route::delete('/projects/{projectId}/invitations/{invitationId}', [ProjectController::class, 'revokeInvitation']);
            Route::get('/projects/{projectId}/members', [ProjectController::class, 'members']);
            Route::put('/projects/{projectId}/members/{memberId}', [ProjectController::class, 'updateMember']);
            Route::delete('/projects/{projectId}/members/{memberId}', [ProjectController::class, 'removeMember']);
            Route::delete('/projects/{projectId}', [ProjectController::class, 'deleteProject']);
            Route::get('/invitations', [ProjectController::class, 'pendingInvitations']);
            Route::post('/invitations/{invitationId}/accept', [ProjectController::class, 'acceptInvitation']);
        });
    });
});
